# Generated by Django 4.1.3 on 2022-11-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_profile_group_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
